name: CI
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: npm install eslint
    # - name: set ESLint config
    #   run: ./node_modules/.bin/eslint --init
    - name: Run ESLint
      run: ./node_modules/.bin/eslint app.js
